<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-02T08:03:07 IST" name="Suite" finished-at="2025-01-02T08:03:14 IST" duration-ms="6978">
    <groups>
      <group name="ErrorHandlings">
        <method signature="ErrorValidations.incorrectCredentialsTest()[pri:0, instance:seleniumFrameworkPractice.refactor.tests.ErrorValidations@42a48628]" name="incorrectCredentialsTest" class="seleniumFrameworkPractice.refactor.tests.ErrorValidations"/>
      </group> <!-- ErrorHandlings -->
    </groups>
    <test started-at="2025-01-02T08:03:07 IST" name="ErrorValidations" finished-at="2025-01-02T08:03:14 IST" duration-ms="6878">
      <class name="seleniumFrameworkPractice.refactor.tests.ErrorValidations">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumFrameworkPractice.refactor.tests.ErrorValidations@42a48628]" started-at="2025-01-02T08:03:07 IST" name="launchApplication" finished-at="2025-01-02T08:03:11 IST" duration-ms="4702" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="incorrectCredentialsTest()[pri:0, instance:seleniumFrameworkPractice.refactor.tests.ErrorValidations@42a48628]" started-at="2025-01-02T08:03:11 IST" name="incorrectCredentialsTest" finished-at="2025-01-02T08:03:12 IST" duration-ms="740" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ Incorrect email or password] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ Incorrect email or password] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at seleniumFrameworkPractice.refactor.tests.ErrorValidations.incorrectCredentialsTest(ErrorValidations.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectCredentialsTest -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:seleniumFrameworkPractice.refactor.tests.ErrorValidations@42a48628]" started-at="2025-01-02T08:03:12 IST" name="closeApplication" finished-at="2025-01-02T08:03:13 IST" duration-ms="1350" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- seleniumFrameworkPractice.refactor.tests.ErrorValidations -->
    </test> <!-- ErrorValidations -->
    <test started-at="2025-01-02T08:03:14 IST" name="PlaceOrderTest" finished-at="2025-01-02T08:03:14 IST" duration-ms="1">
    </test> <!-- PlaceOrderTest -->
  </suite> <!-- Suite -->
</testng-results>
